/* Dossiers premium por vino. Datos de ficha de bodega, crítica y práctica de servicio. */
window.WINE_DOSSIERS = {
  "vs-unico-2009": {
    soils: "Aluviales del Duero con gravas, arenas y un fondo calizo. Parcelas viejas de Tinto Fino en Valbuena.",
    elevation: "700–900 m",
    vineyard: "Pago de Vega Sicilia. Viticultura de baja carga, vendimia manual y selección grano a grano.",
    vinification: "Fermentación en depósitos de madera. Crianza total ~10 años entre barrica francesa/americana y botella antes de salir.",
    elevage: "36 meses en barrica + afinado largo en calados de la finca.",
    glass: "Copa Burdeos amplia (Zalto Universal / Riedel Bordeaux)",
    decant: "90 minutos",
    oxygen: "Necesita aire. Abrir y decantar; no servir del cuello.",
    history: "Único es el gran vino de Vega Sicilia desde 1915. La 2009, añada cálida, se mostró más fresca de lo esperado en cata a ciegas de Luis Gutiérrez.",
    market: { low: 480, mid: 600, high: 720, trend: "Firme. Pocas botellas en mercado secundario." },
    similar: ["vs-unico-2014", "vega-valbuena-2019", "pingus-2018"],
    awards: ["WA 97 (Gutiérrez)", "WS 96", "Decanter 97", "Peñín 97"]
  },
  "vs-unico-2014": {
    soils: "Gravas y calizas de Valbuena de Duero.",
    elevation: "700–900 m",
    vineyard: "Viñas viejas de Tinto Fino con un porcentaje de Cabernet Sauvignon histórico de la finca.",
    vinification: "Crianza clásica Único: años de barrica y botella en la propia bodega.",
    elevage: "Más de una década antes de comercialización.",
    glass: "Copa Burdeos amplia",
    decant: "2 horas",
    oxygen: "Todavía primario. Decantar largo si se abre ahora.",
    history: "Estilo más tenso que 2009. Añada de guarda.",
    market: { low: 450, mid: 560, high: 650, trend: "Al alza al ir saliendo al mercado." },
    similar: ["vs-unico-2009", "pingus-2018"],
    awards: ["WA 96", "Peñín 97", "Decanter 96"]
  },
  "pingus-2018": {
    soils: "Arcillas calcáreas y gravas junto al Duero. Viñas prefiloxéricas en vaso.",
    elevation: "750–800 m",
    vineyard: "Parcelas diminutas en Quintanilla de Onésimo. Agricultura biodinámica de Peter Sisseck.",
    vinification: "Pisado, fermentación con raspón parcial, crianza en barrica francesa de grano fino.",
    elevage: "18–22 meses. Mínima intervención.",
    glass: "Copa Borgoña o Burdeos amplio",
    decant: "60–90 min (solo si se abre joven)",
    oxygen: "Textura ya sedosa; no airear en exceso en apogeo.",
    history: "Pingus nació en 1995 y se convirtió en el mito moderno de Ribera.",
    market: { low: 1200, mid: 1500, high: 1800, trend: "Muy ilíquido. Asignación." },
    similar: ["vs-unico-2009", "lermita-2019"],
    awards: ["WA 99", "Peñín 99", "Decanter 98"]
  },
  "tondonia-reserva-2011": {
    soils: "Aluviales del Ebro en el meandro de Viña Tondonia, Haro. Cantos rodados sobre limos.",
    elevation: "430–500 m",
    vineyard: "Viñedo propio desde 1913. Tempranillo con Garnacha, Graciano y Mazuelo.",
    vinification: "Fermentación en tinos de roble. Crianza 6 años en barrica usada de 225 l, trasiegos manuales.",
    elevage: "Clarificado con claras. Embocado y reposo en botella en calados.",
    glass: "Copa Rioja / Borgoña media",
    decant: "20–30 min (quitar posos)",
    oxygen: "Ya abierto. Un rato en copa basta.",
    history: "R. López de Heredia Viña Tondonia nace en Haro en 1877. La finca Tondonia —un meandro del Ebro— se planta en 1913 y da nombre al vino de la casa. No hay consultor externo ni roble nuevo de moda: fermentación en tinos, seis años en barrica usada de 225 litros, trasiego a mano y clarificado con claras. Luego años de botella en calados bajo la bodega.\n\nLa Reserva 2011 salió al mercado cuando otras bodegas ya vendían la 2018. Por eso hoy (2026) está en meseta, no en arranque. Es el estilo que María José López de Heredia mantiene: acidez, cuero fino y fruta roja, sin maquillaje.\n\nPara la mesa: decantar 20 minutos por los posos. Servir a 16–17 °C. Ventana seria 2024–2036; más allá gana terciario y pierde fruta.",
    market: { low: 38, mid: 46, high: 55, trend: "Estable. Muy demandado en restauración." },
    similar: ["muga-prado-enea-2015", "cvne-monopole-2022"],
    awards: ["WA 94", "Decanter 95", "Peñín 94"]
  },
  "riscal-reserva-2019": {
    soils: "Arcillo-calizos de Elciego, Rioja Alavesa.",
    elevation: "400–500 m",
    vineyard: "Tempranillo de pago con Graciano y Mazuelo.",
    vinification: "Crianza 24 meses en barrica americana y francesa.",
    elevage: "Afinado en botella en la ciudad del vino.",
    glass: "Copa Rioja estándar",
    decant: "15 min",
    oxygen: "Listo. Servir sin ceremonia.",
    history: "Marqués de Riscal elabora Reserva desde el s. XIX. Estilo más moderno que Tondonia.",
    market: { low: 18, mid: 22, high: 26, trend: "Estable, gran liquidez." },
    similar: ["tondonia-reserva-2011"],
    awards: ["Peñín 92", "WA 91"]
  },
  "lermita-2019": {
    soils: "Llicorella (pizarra) en costers de Gratallops. Pendientes extremas.",
    elevation: "300–650 m",
    vineyard: "Garnacha centenaria en vaso. Viticultura heroica.",
    vinification: "Vendimia parcela a parcela. Crianza en foudre y barrica.",
    elevage: "14–18 meses.",
    glass: "Copa Borgoña",
    decant: "45–60 min",
    oxygen: "Aún contenido. Gana con aire.",
    history: "L'Ermita es el vino de culto de Álvaro Palacios en Priorat.",
    market: { low: 1100, mid: 1350, high: 1600, trend: "Coleccionista." },
    similar: ["pingus-2018"],
    awards: ["WA 98", "Peñín 99"]
  },
  "pazo-senorans-2023": {
    soils: "Xabre granítico, Rías Baixas (Meis).",
    elevation: "50–150 m",
    vineyard: "Albariño en emparrado. Influencia atlántica.",
    vinification: "Prensado suave, fermentación en acero, lías finas.",
    elevage: "Meses sobre lías. Sin madera.",
    glass: "Copa Riesling / universal estrecha",
    decant: "No",
    oxygen: "Servir frío. No airear.",
    history: "Referencia de Albariño contemporáneo. Beber en 2–4 años.",
    market: { low: 16, mid: 19, high: 22, trend: "Estable." },
    similar: ["cvne-monopole-2022"],
    awards: ["Peñín 92", "WA 91"]
  },
  "cvne-monopole-2022": {
    soils: "Arcillo-calcáreos de Rioja Alta.",
    elevation: "450 m",
    vineyard: "Viura de viñas viejas.",
    vinification: "Crianza con velo / madera usada. Blanco de guarda.",
    elevage: "Meses en barrica y botella.",
    glass: "Copa Borgoña blanca",
    decant: "No necesario",
    oxygen: "Abrir 20 min antes.",
    history: "Monopole es el blanco histórico de CVNE (1915).",
    market: { low: 22, mid: 26, high: 30, trend: "Estable." },
    similar: ["pazo-senorans-2023", "tondonia-reserva-2011"],
    awards: ["WA 93", "Peñín 93"]
  },
  "gramona-iii-lustros-2016": {
    soils: "Calcáreo-arcillosos del Penedès. Corpinnat.",
    elevation: "150–300 m",
    vineyard: "Xarel·lo y Macabeo ecológico / biodinámico.",
    vinification: "Método tradicional. Larga crianza en rima (≈7 años).",
    elevage: "Degüelle reciente a la venta.",
    glass: "Flauta amplia o copa universal",
    decant: "No",
    oxygen: "8–10 °C. No helar.",
    history: "III Lustros es el Corpinnat de guarda de Gramona.",
    market: { low: 38, mid: 45, high: 52, trend: "Estable." },
    similar: ["dom-perignon-2015"],
    awards: ["Peñín 96", "Decanter 95"]
  },
  "dom-perignon-2015": {
    soils: "Craie champenoise. Premier y Grand Cru.",
    elevation: "100–200 m",
    vineyard: "Ensamblaje Chardonnay / Pinot Noir de pueblos históricos.",
    vinification: "Prise de mousse y larga crianza sur lattes.",
    elevage: "≈8 años antes de lanzamiento.",
    glass: "Copa Champagne amplia (no flauta estrecha)",
    decant: "No",
    oxygen: "8–10 °C. Añada solar, ya accesible.",
    history: "Dom Pérignon solo se declara en añadas. 2015 es perfil maduro y tenso.",
    market: { low: 180, mid: 210, high: 240, trend: "Líquido." },
    similar: ["gramona-iii-lustros-2016"],
    awards: ["WA 96", "Decanter 97"]
  },
  "margaux-2016": {
    soils: "Gravas profundas de Margaux sobre lecho arcillo-calizo.",
    elevation: "10–20 m",
    vineyard: "Enclos histórico del Premier Cru. Cabernet Sauvignon dominante.",
    vinification: "Selección parcelaria, crianza 18–24 meses en barrica nueva francesa.",
    elevage: "Afinado en botella en el château.",
    glass: "Copa Burdeos de gran cáliz",
    decant: "2–3 horas si se abre ahora",
    oxygen: "Añada de guarda. Tanino noble aún firme.",
    history: "Premier Grand Cru Classé 1855. 2016 es añada de leyenda en la orilla izquierda.",
    market: { low: 650, mid: 780, high: 900, trend: "Al alza." },
    similar: ["sassicaia-2019", "vs-unico-2009"],
    awards: ["WA 99", "Decanter 100", "WS 97"]
  },
  "sassicaia-2019": {
    soils: "Gravas y arenas de Bolgheri, influencia marina.",
    elevation: "80–350 m",
    vineyard: "Cabernet Sauvignon y Franc. Tenuta San Guido.",
    vinification: "Crianza 24 meses en barrica francesa.",
    elevage: "Un año en botella antes de salir.",
    glass: "Copa Burdeos",
    decant: "45–60 min",
    oxygen: "Ya seductor; gana 4 años.",
    history: "Nació en los 60 como el primer ‘super toscano’ de corte bordelés.",
    market: { low: 280, mid: 330, high: 380, trend: "Firme." },
    similar: ["margaux-2016"],
    awards: ["WA 98", "WS 97"]
  },
  "grange-2018": {
    soils: "Multi-región South Australia (Barossa, McLaren Vale…).",
    elevation: "Variable",
    vineyard: "Shiraz de viñas viejas + toc de Cabernet.",
    vinification: "Crianza 18–20 meses en roble americano nuevo.",
    elevage: "Estilo icónico Penfolds desde 1951.",
    glass: "Copa Syrah amplia",
    decant: "60 min",
    oxygen: "Denso; necesita copa grande.",
    history: "Grange es el icono de Australia. No se declara todas las añadas.",
    market: { low: 500, mid: 650, high: 800, trend: "Coleccionista Asia." },
    similar: ["pingus-2018"],
    awards: ["WA 98", "WS 97"]
  }
};

window.dossierOf = function (w) {
  const d = (window.WINE_DOSSIERS && w && WINE_DOSSIERS[w.id]) || {};
  const isSpark = w && (w.type === "espumoso" || w.type === "blanco");
  return Object.assign({
    soils: "Suelo de la denominación. Consultar ficha de bodega para la parcela exacta.",
    elevation: "—",
    vineyard: w ? (w.appellation + " · " + w.grapes.join(", ")) : "",
    vinification: "Elaboración según el estilo de la casa.",
    elevage: "Crianza en bodega antes de comercializar.",
    glass: isSpark ? "Copa universal o flauta amplia" : "Copa Burdeos / Rioja",
    decant: isSpark ? "No" : "30–60 min",
    oxygen: isSpark ? "Servir frío, sin decantar." : "Abrir con antelación si la estructura es alta.",
    history: w ? (w.producer + " · " + w.region + ".") : "",
    market: { low: 0, mid: 0, high: 0, trend: "Sin serie suficiente." },
    similar: [],
    awards: []
  }, d);
};
